TUGAS 3 PEMBANDINGAN MODEL REGRESI TERHADAP TIAP TAHAP PREPOCESSING DATA

In [1]:
import pandas as pd
import numpy as np

In [2]:
weather=pd.read_csv("Data Cuaca Australia.csv")
weather.tail()

WindSpeed9am  Humidity9am  Pressure9am  Temp9am
142188          15.0         59.0       1024.7      9.4
142189          13.0         51.0       1024.6     10.1
142190          13.0         56.0       1023.5     10.9
142191           9.0         53.0       1021.0     12.5
142192          13.0         51.0       1019.4     15.1

In [3]:
np.sum(weather.isnull())

WindSpeed9am     1348
Humidity9am      1774
Pressure9am     14014
Temp9am           904
dtype: int64

# a. Missing Value

In [4]:
#Mengisi missing value dengan nilai mean di tiap variabelnya
weather['WindSpeed9am']=weather['WindSpeed9am'].fillna(weather['WindSpeed9am'].mean())
weather['Humidity9am']=weather['Humidity9am'].fillna(weather['Humidity9am'].mean())
weather['Pressure9am']=weather['Pressure9am'].fillna(weather['Pressure9am'].mean())
weather['Temp9am']=weather['Temp9am'].fillna(weather['Temp9am'].mean())

In [5]:
np.sum(weather.isnull())

WindSpeed9am    0
Humidity9am     0
Pressure9am     0
Temp9am         0
dtype: int64

In [7]:
weathertanpamv.tail()

WindSpeed9am  Humidity9am  Pressure9am  Temp9am
142188          15.0         59.0       1024.7      9.4
142189          13.0         51.0       1024.6     10.1
142190          13.0         56.0       1023.5     10.9
142191           9.0         53.0       1021.0     12.5
142192          13.0         51.0       1019.4     15.1

Hasil regresi data tanpa missing value

In [8]:
x = weathertanpamv.iloc[:,0:3].values
y = weathertanpamv.iloc[:,3].values

In [9]:
#regresi
import statsmodels.api as sm
model = sm.OLS(y, x).fit() ## sm.OLS(output, input)
predictions = model.predict(x)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.899
Model:                            OLS   Adj. R-squared:                  0.899
Method:                 Least Squares   F-statistic:                 4.212e+05
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:15:54   Log-Likelihood:            -4.5126e+05
No. Observations:              142193   AIC:                         9.025e+05
Df Residuals:                  142190   BIC:                         9.026e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0105      0.002      5.836      0.000       0.007       0.014
x2            -0.1580      0.001   -187.621      0.000      -0.160      -0.156
x3             0.0272   6.95e-05    391.857      0.000       0.027       0.027
==============================================================================
Omnibus:                     1623.513   Durbin-Watson:                   0.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1411.270
Skew:                           0.190   Prob(JB):                    3.52e-307
Kurtosis:                       2.694   Cond. No.                         120.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# b. Missing Value and Outlier

In [10]:
#Mengatasi outlier
from scipy import stats
z=np.abs(stats.zscore(weathertanpamv._get_numeric_data()))
print(z)
weathertanpamvout=weathertanpamv[(z<3).all(axis=1)]
print(weathertanpamvout.shape)

[[0.67766103 0.11389122 1.47545613 0.0135208 ]
 [1.13003399 1.31226479 1.04558606 0.03283169]
 [0.56468009 1.62918835 1.49027923 0.61996332]
 ...
 [0.11320554 0.67841768 0.86659457 0.94057075]
 [0.5651293  0.83687945 0.49601693 0.69335743]
 [0.11320554 0.94252064 0.25884723 0.29163579]]
(139471, 4)


In [11]:
weathertanpamvout.tail()

WindSpeed9am  Humidity9am  Pressure9am  Temp9am
142188          15.0         59.0       1024.7      9.4
142189          13.0         51.0       1024.6     10.1
142190          13.0         56.0       1023.5     10.9
142191           9.0         53.0       1021.0     12.5
142192          13.0         51.0       1019.4     15.1

Hasil regresi data cuaca di australia tanpa missing value dan outlier

In [13]:
x1 = weathertanpamvout.iloc[:,0:3].values
y1 = weathertanpamvout.iloc[:,-1].values

In [14]:
model1 = sm.OLS(y1, x1).fit() ## sm.OLS(output, input)
predictions = model1.predict(x1)

# Print out the statistics
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.899
Model:                            OLS   Adj. R-squared:                  0.899
Method:                 Least Squares   F-statistic:                 4.134e+05
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:16:19   Log-Likelihood:            -4.4230e+05
No. Observations:              139471   AIC:                         8.846e+05
Df Residuals:                  139468   BIC:                         8.846e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0169      0.002      8.763      0.000       0.013       0.021
x2            -0.1552      0.001   -178.950      0.000      -0.157      -0.154
x3             0.0270   7.21e-05    374.311      0.000       0.027       0.027
==============================================================================
Omnibus:                     1999.133   Durbin-Watson:                   0.250
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1682.203
Skew:                           0.206   Prob(JB):                         0.00
Kurtosis:                       2.653   Cond. No.                         129.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# c. Missing Value dan Transformasi

In [15]:
data=weathertanpamv.iloc[:,0:3]
#normalisasi
from sklearn.preprocessing import normalize
xnorm=normalize(data,norm='l2') #default norm l2, other are l1 and max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()

0         1         2
142188  0.014613  0.057476  0.998240
142189  0.012671  0.049710  0.998683
142190  0.012682  0.054628  0.998426
142191  0.008803  0.051838  0.998617
142192  0.012736  0.049963  0.998670

In [16]:
#softmax
def softmax(data):
    return np.exp(data) / np.sum(np.exp(data),axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft.tail())

               0         1         2
142188  0.000007  0.000007  0.000007
142189  0.000007  0.000007  0.000007
142190  0.000007  0.000007  0.000007
142191  0.000007  0.000007  0.000007
142192  0.000007  0.000007  0.000007


Hasil regresi data tanpa missing value dan mentransformasi data

In [19]:
x2 = xsoft.iloc[:,0:3].values
y2 = weathertanpamv.iloc[:,-1].values

In [20]:
model2 = sm.OLS(y2, x2).fit() ## sm.OLS(output, input)
predictions = model2.predict(x2)

# Print out the statistics
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.900
Model:                            OLS   Adj. R-squared:                  0.900
Method:                 Least Squares   F-statistic:                 4.287e+05
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:16:58   Log-Likelihood:            -4.5013e+05
No. Observations:              142193   AIC:                         9.003e+05
Df Residuals:                  142190   BIC:                         9.003e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          1.279e+06   2.52e+05      5.069      0.000    7.84e+05    1.77e+06
x2         -2.165e+07   1.12e+05   -193.494      0.000   -2.19e+07   -2.14e+07
x3          2.278e+07   2.89e+05     78.861      0.000    2.22e+07    2.33e+07
==============================================================================
Omnibus:                     1609.777   Durbin-Watson:                   0.253
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1384.837
Skew:                           0.185   Prob(JB):                    1.93e-301
Kurtosis:                       2.689   Cond. No.                         303.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# d. Missing Value, Outlier, dan Transformasi

In [21]:
data1=weathertanpamvout.iloc[:,0:3]
from sklearn.preprocessing import normalize
xxnorm=normalize(data1,norm='l2') #default norm l2, other are l1 and max
xxnorm=pd.DataFrame(xxnorm)
xxnorm.tail()

0         1         2
139466  0.014613  0.057476  0.998240
139467  0.012671  0.049710  0.998683
139468  0.012682  0.054628  0.998426
139469  0.008803  0.051838  0.998617
139470  0.012736  0.049963  0.998670

In [22]:
#softmax
def softmax(data1):
    return np.exp(data1) / np.sum(np.exp(data1),axis=0)
xxsoft=softmax(xxnorm)
xxsoft=pd.DataFrame(xxsoft)
print(xxsoft.tail())

               0         1         2
139466  0.000007  0.000007  0.000007
139467  0.000007  0.000007  0.000007
139468  0.000007  0.000007  0.000007
139469  0.000007  0.000007  0.000007
139470  0.000007  0.000007  0.000007


Hasil regresi data tanpa missing value, tanpa oulier, dan mentransformasi data

In [24]:
x3 = xxsoft.iloc[:,0:3].values
y3 = weathertanpamvout.iloc[:,-1].values

In [25]:
model3 = sm.OLS(y3, x3).fit() ## sm.OLS(output, input)
predictions = model3.predict(x3)

# Print out the statistics
model3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                 4.210e+05
Date:                Sun, 10 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:17:18   Log-Likelihood:            -4.4115e+05
No. Observations:              139471   AIC:                         8.823e+05
Df Residuals:                  139468   BIC:                         8.823e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          2.101e+06   2.68e+05      7.852      0.000    1.58e+06    2.63e+06
x2         -2.089e+07   1.13e+05   -185.460      0.000   -2.11e+07   -2.07e+07
x3          2.116e+07   3.03e+05     69.755      0.000    2.06e+07    2.18e+07
==============================================================================
Omnibus:                     1983.135   Durbin-Watson:                   0.250
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1652.098
Skew:                           0.201   Prob(JB):                         0.00
Kurtosis:                       2.650   Cond. No.                         324.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""